# Generated by Django 5.0.6 on 2024-06-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollisionSeverity',
            fields=[
                ('col_sev_no', models.IntegerField(primary_key=True, serialize=False)),
                ('col_sev', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('day_of_week_no', models.IntegerField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='LightCondition',
            fields=[
                ('light_cond_no', models.IntegerField(primary_key=True, serialize=False)),
                ('light_cond', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoadClass',
            fields=[
                ('road_class_no', models.IntegerField(primary_key=True, serialize=False)),
                ('road_class', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoadSurfaceCondition',
            fields=[
                ('road_surf_cond_no', models.IntegerField(primary_key=True, serialize=False)),
                ('road_surf_cond', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoadType',
            fields=[
                ('road_type_no', models.IntegerField(primary_key=True, serialize=False)),
                ('road_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherCondition',
            fields=[
                ('weather_cond_no', models.IntegerField(primary_key=True, serialize=False)),
                ('weather_cond', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Collision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collision_ref', models.IntegerField(db_index=True)),
                ('uk_grid_ref_x', models.IntegerField()),
                ('uk_grid_ref_y', models.IntegerField()),
                ('no_of_vehicles', models.IntegerField()),
                ('no_of_casualties', models.IntegerField()),
                ('date', models.DateField()),
                ('speed_limit', models.IntegerField()),
                ('collision_severity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.collisionseverity')),
                ('day_of_week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.dayofweek')),
                ('light_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.lightcondition')),
                ('road_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.roadclass')),
                ('road_surface_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.roadsurfacecondition')),
                ('road_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.roadtype')),
                ('weather_condition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='uk_road_accidents.weathercondition')),
            ],
        ),
    ]
